#!/bin/sh

wget ftp://ftp.perforce.com/perforce/r20.2/bin.linux26x86_64/p4d
chmod +x p4d
sudo mv p4d /usr/local/bin
sudo mkdir /perforce_depot
sudo chown mikhail /perforce_depot
sudo mkdir /var/log/perforce
sudo chown mikhail /var/log/perforce
sudo apt-get install daemon
cd /etc/init.d
wget https://raw.githubusercontent.com/SLSNe/linux-perforce-installer/master/p4dservice
chmod +x /etc/init.d/p4dservice
sudo update-rc.d p4dservice defaults
sudo reboot
